apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recycler.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "recycler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "recycler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "recycler.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: recycler
    spec:
      containers:
      - args: {{- toYaml .Values.controllerManager.recycler.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.recycler.image.repository }}:{{ .Values.controllerManager.recycler.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.controllerManager.recycler.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: recycler
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.recycler.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.recycler.containerSecurityContext
          | nindent 10 }}
      nodeSelector: {{- toYaml .Values.controllerManager.nodeSelector | nindent 8 }}
      securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}
      serviceAccountName: {{ include "recycler.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      tolerations: {{- toYaml .Values.controllerManager.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.controllerManager.topologySpreadConstraints
        | nindent 8 }}
