apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recycler.fullname" . }}-controller-manager
  namespace: {{ include "recycler.namespace" . }}
  labels:
    control-plane: controller-manager
  {{- include "recycler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "recycler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "recycler.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: recycler
    spec:
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --metrics-bind-address=:8443
        - --health-probe-bind-address=:8081
        {{- if .Values.controllerManager.manager.debug }}
        - --zap-log-level=1
        - --zap-devel=true
        {{- end }}
        env:
        {{- with .Values.controllerManager.manager.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: recycler
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
      securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}
      serviceAccountName: {{ include "recycler.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
