apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the default base configuration
resources:
  - ../../default

# Patch to enable debug logging
patches:
  - path: manager_debug_patch.yaml
    target:
      kind: Deployment
      name: controller-manager
