name: Manifests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-manifests:
    name: Verify manifests are up to date
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone the code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: go.mod

      - name: Generate manifests
        run: |
          make manifests

      - name: Generate helm charts
        run: |
          make helm

      - name: Check for changes
        id: verify
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "The following files have changes:"
            git status --porcelain
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit manifest changes
        if: steps.verify.outputs.changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: 'chore: update manifests and helm charts'
          file_pattern: 'config/** helm-charts/**'
